import {Router} from 'express';
import {createStore, getStores, getStore, updateStore, deleteStore} from '../controllers/store.controller.js';
import {authRequired} from '../middlewares/validateToken.js';
const router = Router();
router.post('/store', authRequired, createStore);
router.get('/store', authRequired, getStores);
router.get('/store/:id', authRequired, getStore);
router.put('/store/:id', authRequired, updateStore);
router.delete('/store/:id', authRequired, deleteStore);
export default router;